### ISSUE TITLE
Node.JS 7.4.0 Update Brakes gfmtoc

### ISSUE THREAD

**Issue by tajmone** [hail2u/node-gfmtoc#4] opened 2017-01-27 00:17 UTC
After updating to Node.JS v7.4.0 I started experiencing the following problem with gfmtoc:

The hash `#` in gfmtoc's opening tag `<!-- #toc -->` is now self-referenced and rendered as a level one header entry in the final TOC:
```
<!-- #toc -->
-   [<!-- /toc -->](#---toc---)
-   [About PP](#about-pp)
-   [Introduction](#introduction)

<!-- /toc -->
```

Something has changed in the way html comments are being parsed.

**Comment by hail2u** [comment] 2017-01-27 01:29
Cannot reproduced on my machine with Windows 10, Node.js v7.4.0, gfmtoc v0.2.1, and marked v0.3.6.

It seems `<!-- #toc -->` was mistakenly parsed as heading by marked. Can you upload a reproducible markdown content?

**Comment by tajmone** [comment] 2017-01-27 09:50
You're right, and it's strange: I've done more tests and it seems that this error only show up with some documents (which didn't produce this error before the update).

So, I've tried to isolate the culprit by exclusion, and after many tests I've isolated the minimum markdown source that causes the error:

```markdown
# XXX

<!-- #toc -->
<!-- /toc -->
-------------
```

There is something about the combination of an horizontal-ruler following the toc closing tag (unspaced) and the presence of a pre-toc H1 header. If you add a blank line after the closing tag, or remove the first header level 1, the problem doesn't show up.

As I said, most documents that now show this error were working fine before.

PS: Also tested on Win10 x64.

**Comment by hail2u** [comment] 2017-01-27 10:12
Thanks, reproduced, and it is very interesting.

However, It is hard to fix on my side, and this should be fixed by marked. I’ll add notes about this behaviour to README.

**Closed as completed** 2017-01-27 10:31 UTC
Labels: wontfix

**Comment by tajmone** [comment] 2017-01-27 10:35
Strange indeed ... but it looks like something has changed in Node itself because I had updated all installed packages very recently, and my guessing is that marked hasn't been changed since.

Being (probably) a string-parsing related issue, it could have unexpected side-effects on all sorts of applications and libraries. Not so cool (and not so easy to pin-down either, apparently).
